### ISSUE TITLE
No Appendix in origin paper

### ISSUE THREAD

**Issue by Zessay** [fuxiAIlab/RL4RS#1]
Thanks for this repo! I find the section 4.2 of the paper says that we can know more about data details in `Appendix C`, and the section 5.1 says that more details about the environment simulation model are shown in `Appendix D`. However, I can't find any appendix in the paper from [this url ](https://arxiv.org/pdf/2110.11073.pdf) shown in the repo. Maybe forget to add appendix to the paper? Or where can I find all the appendix? ~~ Thanks again!

**Comment by asdqsczser** [comment]
Thanks for this reminding! The paper is still in progress, as well as the appendix. All details are in the code. Please see https://github.com/fuxiAIlab/RL4RS/tree/main/rl4rs/nets for the details of environment simulation models.
